### ISSUE TITLE
TypeScript

### ISSUE THREAD

**Issue by petrbela** [superfaceai/passport-twitter-oauth2#13]
Would it be possible to add TypeScript definitions for the package?

**Comment by jnv** [comment]
Definitely, I think it might be even easier to rewrite the whole thing to TypeScript, what do you think @janhalama?

**Comment by janhalama** [comment]
I agree that rewriting the code to TypeScript is the best solution. I will come with PR.

**Comment by dev-bre** [comment]
i would be interested in ts types as well.

**Comment by jnv** [comment]
We've just released v1.2.0 of the package which includes types. Let us know if it works for you!
