### ISSUE TITLE
passReqToCallback doesn't work in typescript

### ISSUE THREAD

**Issue by jfrader** [superfaceai/passport-twitter-oauth2#43]
StrategyOptionWithRequest cannot be used with TwitterStrategy

![image](https://github.com/superfaceai/passport-twitter-oauth2/assets/1530811/6a2bc794-4e26-4b1a-99d1-06f8871e0d1c)

Same when using options as an object straight into TwitterStrategy, and the verify function has the same problem, cannot get the types for passReqToCallback

**Comment by janhalama** [comment]
Hi,
I can confirm that the option passReqToCallback can not be se to true and is not supported by the verify function. I will open PR with a fix.

Jan

**Comment by jfrader** [comment]
It works in runtime if I cast `true as false` and I also set my function with typed parameters to have the request as the first param.
It's just the types that are wrong and makes me have to cast as any and as false.

Thank you so much!

**Comment by janhalama** [comment]
Hi @jfrader,
I released [v1.2.4-beta.0](https://www.npmjs.com/package/@superfaceai/passport-twitter-oauth2/v/1.2.4-beta.0) version with a fix, can you test it, and confirm that the types are now OK.

**Comment by jfrader** [comment]
@janhalama Thank you very much, I will test this today and get back to you.

**Comment by janhalama** [comment]
The fix has been released in [v1.2.4](https://github.com/superfaceai/passport-twitter-oauth2/releases/tag/v1.2.4).
