### ISSUE TITLE
First time auth, success redirect is wrong

### ISSUE THREAD

**Issue by DobromirKirovLime** [superfaceai/passport-twitter-oauth2#47]
Hello, when the user is authenticating for the first time the twitter auth page prompts him to login somehow to twitter and on the top of the browser the url has a query parameter `https://twitter.com/i/flow/login?redirect_after_login=my_redireect_login_url` which is fine, but when the user logs in successfully the actual redirect goes to `https://x.com`; Every next attempt to auth is working as expected, the screen says 'Authorize App' and i can execute my actions on the backend after that, what am i missing here?

I am using Nest JS, here is a code snippet: 

### My Twitter strategy guard
```
import { Injectable } from '@nestjs/common';
 import { ConfigService } from '@nestjs/config';
 import { PassportStrategy } from '@nestjs/passport';
 import { Strategy } from '@superfaceai/passport-twitter-oauth2';

 @Injectable()
 export class TwitterFollowAuthService extends PassportStrategy(
   Strategy,
   'twitter-follow',
 ) {
   constructor(configService: ConfigService) {
     const BE_URL = configService.get<string>('BE_URL');
 
     super({
       clientType: 'confidential',
       clientID: configService.get<string>('TWITTER_CLIENT_ID'),
       clientSecret: configService.get<string>('TWITTER_CLIENT_SECRET'),
       callbackURL: `${BE_URL}/auth/twitter/callback`,
       scope: ['follows.write', 'users.read', 'tweet.read'],
     });
   }

   async validate(token: string, tokenSecret: string, profile: any) {
     return { ...profile, token, tokenSecret };
   }
 }
```
### The actual endpoint
 ```
 @Get('v1/public/auth/twitter/callback')
  @UseGuards(AuthGuard('twitter-follow'))
  async twitterAuthRedirect(@Req() req, @Res() res: Response) {
    return this.twitterService.twitterFollow(req, res);
  }
```

I want to clarify that there is no other issues, just that initial redirect, not sure if its something to do with twitter/x provider;

Thanks in advance!

### EDIT
Actually there are two query parameters for redirect, `redirect_after_login` and `redirect_uri` and redirect after login seems to be empty:  

`https://twitter.com/i/flow/login?redirect_after_login=%2Fi%2Foauth2%2Fauthorize%3Fresponse_type%3Dcode%26redirect_uri%3Dhttp%253A%252F%252Flocalhost%253A8080%252Fv1%252Fpublic%252Fauth%252Ftwitter%252Fretweet%26scope%3Dtweet.read%2520users.read%2520users.read%26code_challenge%3D...%26code_challenge_method%3D...%26client_id%...`

**Comment by janhalama** [comment]
I was able to reproduce the issue only in case of Google federated authentication, when I use username and password I am redirected back correctly, I did not tested Apple federated authentication.

Here is an issue open for 2 years on X developers forum: https://devcommunity.x.com/t/twitter-oauth-v2-bug-when-user-use-sign-in-with-google-to-sign-in-to-twitter/169651

**Comment by DobromirKirovLime** [comment]
> I was able to reproduce the issue only in case of Google federated authentication, when I use username and password I am redirected back correctly, I did not test Apple federated authentication.
> 
> Here is an issue open for 2 years on X developers forum: https://devcommunity.x.com/t/twitter-oauth-v2-bug-when-user-use-sign-in-with-google-to-sign-in-to-twitter/169651

Yes, I can confirm that as well, thank you for the response!
