### ISSUE TITLE
Something went wrong

### ISSUE THREAD

**Issue by AdamJessop** [superfaceai/passport-twitter-oauth2#9]
Hi, is this still maintained etc?

I am getting a screen stating that something went wrong and:
"You weren’t able to give access to the App. Go back and try logging in again."

I have also tried your sample twitter-demo app and had the same result. Is there something that needs updating here?

**Comment by AdamJessop** [comment]
Actually, using the demo app, I managed to get it to work once I had added the correct callback URL to my app, however that is not the issue with my implementation it seems. I am struggling to see the difference. 

I am integrating with nestjs and here is my class in a nutshell:

```
import { Profile, Strategy } from '@superfaceai/passport-twitter-oauth2';
import { PassportStrategy } from '@nestjs/passport';

export class TenantTwitterAuthStrategy extends PassportStrategy(Strategy, 'twitter') {

    constructor(
         config: ConfigService,
    ) {
        super({
            clientID: onfig.get('TWITTER_CLIENT_ID'),
            clientSecret: config.get('TWITTER_CLIENT_SECRET'),
            callbackURL: `${config.get('HOST')}/auth/tenant/twitter/redirect`,
            clientType: 'private',
            passReqToCallback: true,
        });
        console.log('callback', `${config.get('HOST')}/auth/tenant/twitter/redirect`);
    }
    
    .....
...

**Comment by AdamJessop** [comment]
Resolved, I see the demo was automatically injecting scope, I wasn't declaring it.

**Comment by jnv** [comment]
Glad to see you figured it out! 👍

Yeah, we still maintain this package, feel free to open issue or PR if you have any suggestions on improving the docs or the demo app.
